### ISSUE TITLE
图片显示失败

### ISSUE THREAD

**Issue by Philo-github** [zh-jp/melanoma-image-segmentation#1]
按照您的搭建指南，已经全部将分割相关文件放在对应路径中，其中的一个问题是，将 **UPLOAD_FOLDER = './front/static/tmp/'** ,可以在tmp中保存结果，但是在web端图片显示失败嘞，这是为啥？
**显示如下：**
![image](https://github.com/zh-jp/melanoma-image-segmentation/assets/72772679/c7ac4d6f-afdc-40bf-aca1-b087564b07ce)

**Comment by zh-jp** [comment]
源文 `UPLOAD_FOLDER = 'static/tmp/'`是否奏效？

**Comment by zh-jp** [comment]
你好！

我尝试了源代码`UPLOAD_FOLDER = 'static/tmp/'`，是能正常运行的，你的问题是由于：Flask 默认静态文件存放在 static 文件夹下，其他文件夹下的文件会导致无法访问。请保证和app.py同目录下，存在static文件夹，存放template所需的静态文件。
